name: Static files check

on:
  pull_request:
    paths:
      - 'static/**'

jobs:
  commentstatic:
    name: Warning for new static files in Django site
    runs-on: ubuntu-latest
    steps:
      - name: comment PR
        uses: unsplash/comment-on-pr@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          msg: "Static files changed!"